### ISSUE TITLE
old versions of dependencies won't build on my system

### ISSUE THREAD

**Issue by ITwrx** [BroderickCarlin/openweather#1]
hi,
i'm hoping to use this for my little learning program, but it won't build due to some ancient version of openssl being required as a dependency of one of openweather's dependencies. i notice that openweather dependencies are at much newer versions than what's called for in the openweather cargo.toml so i'm guessing they have long since fixed added support for newer versions of openssl.
Any chance you could update this crate to use the newer versions of those crates?
thanks

**Comment by BroderickCarlin** [comment]
What exactly is the issue you are seeing? I just recloned this repo and was able to build/run the example without issue.

**Comment by BroderickCarlin** [comment]
I am unable to duplicate this issue and am going to go ahead and close after no response. If the issue persists let me know and I will look into it

**Comment by ITwrx** [comment]
TLDR; AFAICT, openweather won't build on up to date linux due to outdated dependencies. would probably build fine if it were made compat with latest versions of it's dependencies.

it doesn't build (when i reported this) on any linux distro that doesn't use an ancient (likely vulnerable) version of openssl (i don't remember which one). the dependencies in the cargo.toml use old versions, one of which (i don't remember which one) requires an ancient version of openssl. what are you successfully building on?  i'm using arch linux (latest stable upstream). i had to install updated versions of crate dependencies and then manually add your code to my project b/c your crate wouldn't build as-is with latest versions of it's dependencies and ancient versions of openssl are not an option for me.

**Comment by BroderickCarlin** [comment]
I'm able to build without issue on macOS Mojave 10.14.4. If you have a fix for the issue on your platform please feel free to open a PR with the changes needed

**Comment by ITwrx** [comment]
if i ever go back to that little project i'll keep that in mind. thanks.
